# Generated by Django 4.2.20 on 2025-04-18 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tes_direction', models.CharField(max_length=200, verbose_name="Test yo'nalishi")),
            ],
            options={
                'verbose_name': "Test ma'lumoti",
                'verbose_name_plural': "Test ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='UserTestTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainapp.testinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ismi')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('correct', models.PositiveIntegerField(verbose_name="To'gri javoblar soni")),
                ('wrong', models.PositiveIntegerField(verbose_name='Xato javoblar soni')),
                ('ball', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brainapp.testinformation', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar natijalari',
                'verbose_name_plural': 'Foydalanuvchilar natijalari',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer_A', models.CharField(max_length=255, verbose_name='A Javob')),
                ('answer_B', models.CharField(max_length=255, verbose_name='B Javob')),
                ('answer_C', models.CharField(max_length=255, verbose_name='C Javob')),
                ('answer_D', models.CharField(max_length=255, verbose_name='D Javob')),
                ('correct', models.CharField(choices=[('--', '--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='--', max_length=2, verbose_name="Tog'ri javob")),
                ('answer', models.CharField(choices=[('--', '--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='--', max_length=2, verbose_name='Tanlagan javobi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javoblari',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
            },
        ),
        migrations.CreateModel(
            name='ReactionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='Reaction Test', max_length=100)),
                ('reaction_time', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('average_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer_A', models.CharField(max_length=255, verbose_name='A Javob')),
                ('answer_B', models.CharField(max_length=255, verbose_name='B Javob')),
                ('answer_C', models.CharField(max_length=255, verbose_name='C Javob')),
                ('answer_D', models.CharField(max_length=255, verbose_name='D Javob')),
                ('correct', models.CharField(choices=[('--', '--'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='--', max_length=2, verbose_name="To'g'ri javob")),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm')),
                ('img', models.BooleanField(default=False, verbose_name='Rasm mavjudmi')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brainapp.testinformation', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test savollari',
                'verbose_name_plural': 'Test savollari',
            },
        ),
        migrations.CreateModel(
            name='MemoryGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='Memory Game', max_length=100)),
                ('time', models.CharField(max_length=10)),
                ('moves', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
