# Generated by Django 4.2.20 on 2025-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='presentations/', verbose_name='Fayl')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Prezentatsiya',
                'verbose_name_plural': 'Prezentatsiyalar',
            },
        ),
    ]
